# Generated by Django 5.0.3 on 2024-11-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rustdesdevice_ip_rustdeskpeer_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='GithubRun',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=100, verbose_name='uuid')),
                ('status', models.CharField(max_length=100, verbose_name='status')),
            ],
        ),
    ]
